global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "flask_app"
    metrics_path: /metrics        # 👈 this is the fix
    static_configs:
      - targets: ["app:8000"]     # service name from docker-compose
