name: Auto Deploy on Push

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script_stop: true
          script: |
            set -euo pipefail
            cd "${{ secrets.PROD_PATH }}"

            echo "Pulling latest code..."
            git fetch --all
            git reset --hard origin/main

            echo "Rebuilding & restarting containers..."
            docker compose down
            docker compose build --pull
            docker compose up -d --remove-orphans

            docker system prune -f
